apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: dineshvaishnav/web-server:latest  # 👈 use your image here
        ports:
        - containerPort: 80  # 👈 change this if your app runs on a different port

